/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.81
 * Generated at: 2022-07-04 02:12:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1098736424000L));
    _jspx_dependants.put("jar:file:/C:/Randy/tomcat/webapps/ROOT/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098736290000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" \r\n");

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3c.org/TR/1999/REC-html401-19991224/loose.dtd\">\r\n");
      out.write("<HTML xmlns=\"http://www.w3.org/1999/xhtml\"><HEAD><TITLE>Rental2022</TITLE>\r\n");
      out.write("<META content=\"text/html; charset=utf-8\" http-equiv=Content-Type><LINK \r\n");
      out.write("rel=stylesheet type=text/css href=\"image/WebResource.axd\">\r\n");
      out.write("<META name=description \r\n");
      out.write("content=Richdmon City has a wide range of apartments, condominiums, apartments for rent, and shared houses.><LINK \r\n");
      out.write("rel=stylesheet type=text/css href=\"image/public.css\"><LINK \r\n");
      out.write("rel=stylesheet type=text/css href=\"styles/ershou.css\">\r\n");
      out.write("<SCRIPT src=\"js/aJax.js\"></SCRIPT>\r\n");
      out.write("\r\n");
      out.write("<STYLE type=text/css>\r\n");
      out.write(".style1 \r\n");
      out.write("{\r\n");
      out.write("	COLOR: #0000ff\r\n");
      out.write("}\r\n");
      out.write(".STYLE2 {color: #FF0000}\r\n");
      out.write(".STYLE5 {color: #FF6600}\r\n");
      out.write("\r\n");
      out.write("</STYLE>\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("		function reloadCode(){\r\n");
      out.write("		//alert(document.getElementById(\"yzm\").src);\r\n");
      out.write("		document.getElementById(\"yzm\").src=\"yanzhengma?date=\"+new Date();\r\n");
      out.write("		}\r\n");
      out.write("		</script>\r\n");
      out.write("\r\n");
      out.write("<META name=GENERATOR content=\"MSHTML 8.00.6001.18702\"></HEAD>\r\n");
      out.write("<BODY>\r\n");
      out.write("		<div id=\"whitecontent\" class=\"white_content\">\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"black_overlay\" id=\"fade\"></div>\r\n");
      out.write("<!--未登录-->\r\n");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!--未登录-->\r\n");
      out.write("<!--已登录-->\r\n");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!--已登录-->\r\n");
      out.write("  <SCRIPT type=text/javascript src=\"image/WebResource.css\"></SCRIPT>\r\n");
      out.write("  <SCRIPT src=\"image/ajax.js\"></SCRIPT>\r\n");
      out.write("\r\n");
      out.write("<SCRIPT src=\"image/index.js\"></SCRIPT>\r\n");
      out.write("\r\n");
      out.write("<div id=\"aJaxDiv\" style=\"display:none\">\r\n");
      out.write("  <TABLE border=0 width=\"100%\">\r\n");
      out.write("    <TBODY>\r\n");
      out.write("      <TR>\r\n");
      out.write("        <TD height=28 background=image/index_2.gif align=left><TABLE border=0 cellSpacing=0 cellPadding=0 width=950 align=center \r\n");
      out.write("      height=28>\r\n");
      out.write("          <TBODY>\r\n");
      out.write("            <TR>\r\n");
      out.write("              <TD height=28><SPAN style=\"DISPLAY: block\" id=Top1_1_divwei>\r\n");
      out.write("                <TABLE border=0 cellSpacing=0 cellPadding=0 width=450>\r\n");
      out.write("                  <TBODY>\r\n");
      out.write("                    <TR>\r\n");
      out.write("                      <TD>欢迎您：<span id=\"usrNameSpan\"></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href=\"./getMyPub\">去管理中心</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href=\"./exit\">&nbsp;注销登录</a></TD>\r\n");
      out.write("                    </TR>\r\n");
      out.write("                  </TBODY>\r\n");
      out.write("                </TABLE>\r\n");
      out.write("              </SPAN><SPAN \r\n");
      out.write("            style=\"DISPLAY: none\" id=Top1_1_divyi></SPAN></TD>\r\n");
      out.write("              <TD colSpan=2 \r\n");
      out.write("            align=right>Randy Tan</TD>\r\n");
      out.write("            </TR>\r\n");
      out.write("          </TBODY>\r\n");
      out.write("        </TABLE></TD>\r\n");
      out.write("      </TR>\r\n");
      out.write("    </TBODY>\r\n");
      out.write("  </TABLE>\r\n");
      out.write("</div>\r\n");
      out.write("<TABLE border=0 width=950 align=center height=70>\r\n");
      out.write("  <TBODY>\r\n");
      out.write("  <TR>\r\n");
      out.write("    <TD width=200><A href=\"index.jsp\"><IMG border=0 \r\n");
      out.write("      src=\"image/index_logo.gif\" width=200 height=65></A></TD>\r\n");
      out.write("    <TD width=375 align=right><IMG src=\"image/xiaoheng1.gif\" \r\n");
      out.write("      width=363 height=60></TD>\r\n");
      out.write("    <TD width=375 align=right><IMG src=\"image/xiaoheng2.gif\" \r\n");
      out.write("      width=363 height=60></TD></TR></TBODY></TABLE>\r\n");
      out.write("<TABLE border=0 cellSpacing=0 cellPadding=0 width=950 align=center></TABLE>\r\n");
      out.write("<TABLE border=0 cellSpacing=0 cellPadding=2 width=950 bgColor=#bbd6f1 \r\n");
      out.write("align=center>\r\n");
      out.write("  <TBODY>\r\n");
      out.write("  <TR>\r\n");
      out.write("    <TD bgColor=#ffffff height=27 vAlign=center>\r\n");
      out.write("      <TABLE border=0 cellSpacing=0 cellPadding=0 width=\"100%\">\r\n");
      out.write("        <TBODY>\r\n");
      out.write("        <TR>\r\n");
      out.write("          <TD width=\"26%\">　<SPAN class=font-14><A \r\n");
      out.write("            href=\"index.jsp\">Home</A>&gt; Rental Information</SPAN></TD>\r\n");
      out.write("          <TD width=\"67%\" align=right>&nbsp;</TD>\r\n");
      out.write("          <TD vAlign=center width=\"7%\" \r\n");
      out.write("  align=middle></TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE>\r\n");
      out.write("<TABLE border=0 cellSpacing=0 cellPadding=0 width=\"100%\" align=center>\r\n");
      out.write("  <TBODY>\r\n");
      out.write("  <TR>\r\n");
      out.write("    <TD height=8></TD></TR></TBODY></TABLE>\r\n");
      out.write("<TABLE border=0 cellSpacing=1 cellPadding=0 width=950 bgColor=#bbd6f1 \r\n");
      out.write("align=center>\r\n");
      out.write("  <form action=\"./search\" method=\"post\" onSubmit=\"return check()\"><TBODY>\r\n");
      out.write("  <TR>\r\n");
      out.write("    <TD bgColor=#ffffff height=25 vAlign=top><TABLE border=0 cellSpacing=2 cellPadding=2 width=920 align=center>\r\n");
      out.write("      <TBODY>\r\n");
      out.write("        <TR>\r\n");
      out.write("          <TD width=857>Area：\r\n");
      out.write("            <label>\r\n");
      out.write("            <select name=\"quyu\" id=\"quyu\">\r\n");
      out.write("              <option value=\"Richmond\">Richmond</option>\r\n");
      out.write("              <option value=\"Downtown\">Downtown</option>\r\n");
      out.write("              <option value=\"Vancouver\">Vancouver</option>\r\n");
      out.write("              <option value=\"White Rock\">White Rock</option>\r\n");
      out.write("              <option value=\"Surrey\">Surrey</option>\r\n");
      out.write("              <option value=\"Burnaby\">Burnaby</option>\r\n");
      out.write("              <option value=\"Coquitlam\">Coquitlam </option>\r\n");
      out.write("              <option value=\"Ladner\">Ladner </option>\r\n");
      out.write("              <option value=\"Tsawwassen\">Tsawwassen</option>\r\n");
      out.write("              <option value=\"West Vancouver\">West Vancouver </option>\r\n");
      out.write("              <option value=\"Langley \">Langley </option>\r\n");
      out.write("            </select>\r\n");
      out.write("            &nbsp;&nbsp;\r\n");
      out.write("            <select name=\"shi\" id=\"shi\">\r\n");
      out.write("              <option value=\"1\">1</option>\r\n");
      out.write("              <option value=\"2\">2</option>\r\n");
      out.write("              <option value=\"3\">3</option>\r\n");
      out.write("              <option value=\"4\">4</option>\r\n");
      out.write("              <option value=\"5\">5</option>\r\n");
      out.write("              <option value=\"6\">6</option>\r\n");
      out.write("              <option value=\"7\">7</option>\r\n");
      out.write("              <option value=\"8\">8</option>\r\n");
      out.write("              <option value=\"9\">9</option>\r\n");
      out.write("            </select>\r\n");
      out.write("            Room&nbsp;&nbsp;&nbsp;&nbsp;Area：            \r\n");
      out.write("            <input name=\"mianji1\" type=\"text\" id=\"mianji1\" onBlur=\"this.value=this.value.replace(/[^0-9]/g,'');\" \r\n");
      out.write("onkeypress=\"this.value=this.value.replace(/[^0-9]/g,'');\"\r\n");
      out.write("onkeyup=\"this.value=this.value.replace(/[^0-9]/g,'');\" size=\"4\" maxlength=\"4\">\r\n");
      out.write("-\r\n");
      out.write("<input name=\"mianji2\" type=\"text\" id=\"mianji2\" size=\"4\" maxlength=\"4\" onBlur=\"this.value=this.value.replace(/[^0-9]/g,'');\" \r\n");
      out.write("onkeypress=\"this.value=this.value.replace(/[^0-9]/g,'');\"\r\n");
      out.write("onkeyup=\"this.value=this.value.replace(/[^0-9]/g,'');\">\r\n");
      out.write("&nbsp;            &nbsp;Monthly：            \r\n");
      out.write("            <input name=\"yuezu1\" type=\"text\" id=\"yuezu1\" size=\"4\" maxlength=\"4\" onBlur=\"this.value=this.value.replace(/[^0-9]/g,'');\" \r\n");
      out.write("onkeypress=\"this.value=this.value.replace(/[^0-9]/g,'');\"\r\n");
      out.write("onkeyup=\"this.value=this.value.replace(/[^0-9]/g,'');\">\r\n");
      out.write("            -\r\n");
      out.write("            <input name=\"yuezu2\" type=\"text\" id=\"yuezu2\" size=\"4\" maxlength=\"4\" onBlur=\"this.value=this.value.replace(/[^0-9]/g,'');\" \r\n");
      out.write("onkeypress=\"this.value=this.value.replace(/[^0-9]/g,'');\"\r\n");
      out.write("onkeyup=\"this.value=this.value.replace(/[^0-9]/g,'');\">\r\n");
      out.write("            $\r\n");
      out.write("            &nbsp;&nbsp;Location:\r\n");
      out.write("            <input name=\"dizhi\" type=\"text\" id=\"dizhi\">\r\n");
      out.write("            </label></TD>\r\n");
      out.write("          <TD width=49 rowspan=\"2\"><input type=\"submit\" name=\"Submit\" value=\"Search\"></TD>\r\n");
      out.write("        </TR>\r\n");
      out.write("        <TR>\r\n");
      out.write("          <TD></TD>\r\n");
      out.write("        </TR>\r\n");
      out.write("      </TBODY>\r\n");
      out.write("    </TABLE></TD></TR></TBODY></form></TABLE>\r\n");
      out.write("<TABLE border=0 cellSpacing=0 cellPadding=0 width=\"100%\" align=center>\r\n");
      out.write("  <TBODY>\r\n");
      out.write("  <TR>\r\n");
      out.write("    <TD height=8></TD></TR></TBODY></TABLE>\r\n");
      out.write("<TABLE border=0 cellSpacing=0 cellPadding=0 width=950 align=center height=29>\r\n");
      out.write("  <TBODY>\r\n");
      out.write("  <TR>\r\n");
      out.write("    <TD height=29 vAlign=bottom \r\n");
      out.write("background=image/ershouindex_111.gif>\r\n");
      out.write("      <TABLE border=0 cellSpacing=0 cellPadding=0 width=855 height=21>\r\n");
      out.write("        <TBODY>\r\n");
      out.write("        <TR>\r\n");
      out.write("          <TD height=19 width=38>&nbsp;</TD>\r\n");
      out.write("          <TD class=font-cu width=192 align=left>Rental Information</TD>\r\n");
      out.write("          <TD class=font-cu width=68 align=left><a href=\"publish.jsp\"><IMG \r\n");
      out.write("            src=\"image/ershouindex_111_2.gif\" name=\"Imgfabu_1\" width=\"55\" height=\"15\" border=\"0\" \r\n");
      out.write("            id=Imgfabu_1 style=\"CURSOR: hand\"></a></TD>\r\n");
      out.write("          <TD width=557 align=left>Register first<A class=style1 \r\n");
      out.write("            href=\"reg.jsp\" target=_blank>Register</A> \r\n");
      out.write("            Release</TD>\r\n");
      out.write("        </TR></TBODY></TABLE></TD></TR></TBODY></TABLE>\r\n");
      out.write("<TABLE border=0 cellSpacing=1 cellPadding=2 width=950 bgColor=#aacbee \r\n");
      out.write("align=center>\r\n");
      out.write("  <TBODY>\r\n");
      out.write("  <TR>\r\n");
      out.write("    <TD class=lan14cu bgColor=#d3e5f6 height=25 width=52>\r\n");
      out.write("      <DIV align=center>No.</DIV></TD>\r\n");
      out.write("    <TD class=lan14cu bgColor=#d3e5f6 width=74>\r\n");
      out.write("      <DIV align=center>Region</DIV></TD>\r\n");
      out.write("    <TD class=lan14cu bgColor=#d3e5f6 width=182>\r\n");
      out.write("      <DIV align=center>Name of district</DIV></TD>\r\n");
      out.write("    <TD class=lan14cu bgColor=#d3e5f6 width=143>\r\n");
      out.write("      <DIV align=center>Room Type</DIV></TD>\r\n");
      out.write("    <TD class=lan14cu bgColor=#d3e5f6 width=73>\r\n");
      out.write("      <DIV align=center>Direction</DIV></TD>\r\n");
      out.write("    <TD class=lan14cu bgColor=#d3e5f6 width=72>\r\n");
      out.write("      <DIV align=center>Floor</DIV></TD>\r\n");
      out.write("    <TD class=lan14cu bgColor=#d3e5f6 width=59>\r\n");
      out.write("      <DIV align=center>Area</DIV></TD>\r\n");
      out.write("    <TD class=lan14cu bgColor=#d3e5f6 width=60>\r\n");
      out.write("      <DIV align=center>Rent</DIV></TD>\r\n");
      out.write("    <TD class=lan14cu bgColor=#d3e5f6 width=150>\r\n");
      out.write("      <DIV align=center>time</DIV></TD>\r\n");
      out.write("    <TD class=lan14cu bgColor=#d3e5f6 width=34>\r\n");
      out.write("    <DIV align=center>details</DIV></TD></TR>\r\n");
      out.write("	\r\n");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("  </TBODY></TABLE>\r\n");
      out.write("<TABLE border=0 cellSpacing=1 cellPadding=0 width=950 align=center></TABLE>\r\n");
      out.write("<TABLE border=0 cellSpacing=0 cellPadding=0 width=950 align=center>\r\n");
      out.write("  <TBODY>\r\n");
      out.write("  <TR>\r\n");
      out.write("    <TD>");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      out.write("</TD></TR>\r\n");
      out.write("  <TR>\r\n");
      out.write("    <TD>\r\n");
      out.write("      <TABLE border=0 cellSpacing=1 cellPadding=0 width=\"100%\" \r\n");
      out.write("        bgColor=#bbd6f1><TBODY>\r\n");
      out.write("        <TR>\r\n");
      out.write("          <TD bgColor=#ffffff height=27 align=middle>&nbsp;</TD>\r\n");
      out.write("        </TR></TBODY></TABLE></TD></TR>\r\n");
      out.write("  <TR>\r\n");
      out.write("    <TD height=6></TD></TR>\r\n");
      out.write("  <TR>\r\n");
      out.write("    <TD height=21 align=middle><SPAN \r\n");
      out.write("    class=style2>Housing Rental</SPAN></TD>\r\n");
      out.write("  </TR>\r\n");
      out.write("  <TR>\r\n");
      out.write("    <TD height=20 align=middle>Randy Tan<SPAN \r\n");
      out.write("      class=black>&nbsp;&nbsp;&nbsp;</SPAN>7788833603<SPAN \r\n");
      out.write("      class=black>&nbsp;&nbsp;</SPAN>E-mail：Tanguochaopty@gmail.com</TD>\r\n");
      out.write("  </TR>\r\n");
      out.write("  <TR>\r\n");
      out.write("    <TD height=26 align=middle>Richmond<SPAN \r\n");
      out.write("      class=black>&nbsp;&nbsp;</SPAN> V6Y</TD>\r\n");
      out.write("  </TR>\r\n");
      out.write("  <TR>\r\n");
      out.write("    <TD height=26 align=middle>Copyright181.cc All Rights Reserved<SPAN \r\n");
      out.write("      class=black>&nbsp;&nbsp; </SPAN>Randy Tan</TD></TR>\r\n");
      out.write("  <TR>\r\n");
      out.write("    <TD height=40 align=middle>\r\n");
      out.write("      <SCRIPT type=text/javascript>\r\n");
      out.write("var _bdhmProtocol = ((\"https:\" == document.location.protocol) ? \" https://\" : \" http://\");\r\n");
      out.write("document.write(unescape(\"%3Cscript src='\" + _bdhmProtocol + \"hm.baidu.com/h.js%3F5b48cf6d948c70034f7a239f8e5c566d' type='text/javascript'%3E%3C/script%3E\"));\r\n");
      out.write("</SCRIPT>\r\n");
      out.write("    </TD></TR></TBODY></TABLE>\r\n");
      out.write("<SCRIPT src=\"image/tools.js\"></SCRIPT>\r\n");
      out.write("\r\n");
      out.write("<SCRIPT src=\"image/ershou.js\"></SCRIPT>\r\n");
      out.write("</BODY></HTML>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /main.jsp(39,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty sessionScope.usrName}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("<div id=\"login\">\r\n");
          out.write("  <TABLE border=0 width=\"100%\">\r\n");
          out.write("    <TBODY>\r\n");
          out.write("      <TR>\r\n");
          out.write("        <TD height=28 background=image/index_2.gif align=left><TABLE border=0 cellSpacing=0 cellPadding=0 width=950 align=center \r\n");
          out.write("      height=28>\r\n");
          out.write("            <TBODY>\r\n");
          out.write("              <TR>\r\n");
          out.write("                <TD width=\"703\" height=28><SPAN style=\"DISPLAY: block\" id=Top1_1_divwei>\r\n");
          out.write("                  <TABLE border=0 cellSpacing=0 cellPadding=0 width=668>\r\n");
          out.write("                    \r\n");
          out.write("                        <TBODY>\r\n");
          out.write("                          <TR>\r\n");
          out.write("                            <TD width=42>User</TD>\r\n");
          out.write("                            <TD width=107><INPUT style=\"WIDTH: 100px\" id=usrAccount \r\n");
          out.write("                  maxLength=20 type=text name=usrAccount></TD>\r\n");
          out.write("                            <TD width=28 align=middle>Password</TD>\r\n");
          out.write("                            <TD width=100><INPUT style=\"WIDTH: 100px\" id=usrPassword \r\n");
          out.write("                  onkeyup=check13dl() maxLength=20 type=password \r\n");
          out.write("                  name=usrPassword></TD>\r\n");
          out.write("                            <!--<TD width=45 align=middle>Verification</TD>\r\n");
          out.write("                            <TD width=46 align=middle><input name=\"yanzhengma\" type=\"text\" id=\"yanzhengma\" size=\"6\" maxlength=\"4\"></TD>\r\n");
          out.write("                            <TD width=69 align=middle><img src=\"yanzhengma\" alt=\"change \" id=\"yzm\" onClick=\"reloadCode()\"></TD>已登录-->\r\n");
          out.write("                            <TD width=86 align=middle><input type=\"image\" name=\"imageField2\" src=\"image/index_5.gif\" onClick=\"login()\"></TD>\r\n");
          out.write("                            <TD width=\"145\"><a href=\"reg.jsp\">Registration</a></TD>\r\n");
          out.write("                          </TR>\r\n");
          out.write("                        </TBODY>\r\n");
          out.write("                  </TABLE>\r\n");
          out.write("                </SPAN><SPAN \r\n");
          out.write("            style=\"DISPLAY: none\" id=Top1_1_divyi></SPAN></TD>\r\n");
          out.write("                <TD width=\"247\" colSpan=2 \r\n");
          out.write("            align=center>Randy Tan</TD>\r\n");
          out.write("              </TR>\r\n");
          out.write("            </TBODY>\r\n");
          out.write("        </TABLE></TD>\r\n");
          out.write("      </TR>\r\n");
          out.write("    </TBODY>\r\n");
          out.write("  </TABLE>\r\n");
          out.write("</div>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /main.jsp(82,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty sessionScope.usrName}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("  <div id=\"usrInfo\">\r\n");
          out.write("  <TABLE border=0 width=\"100%\">\r\n");
          out.write("    <TBODY>\r\n");
          out.write("      <TR>\r\n");
          out.write("        <TD height=28 background=image/index_2.gif align=left><TABLE border=0 cellSpacing=0 cellPadding=0 width=950 align=center \r\n");
          out.write("      height=28>\r\n");
          out.write("            <TBODY>\r\n");
          out.write("              <TR>\r\n");
          out.write("                <TD width=\"704\" height=28><SPAN style=\"DISPLAY: block\" id=Top1_1_divwei>\r\n");
          out.write("                  <TABLE border=0 cellSpacing=0 cellPadding=0 width=450>\r\n");
          out.write("                        <TBODY>\r\n");
          out.write("                          <TR>\r\n");
          out.write("                            <TD>欢迎您：<span class=\"STYLE2\"><span class=\"STYLE5\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.usrName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</span>&nbsp;</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href=\"./getMyPub\">去管理中心</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href=\"./exit\">&nbsp;注销登录</a></TD>\r\n");
          out.write("                          </TR>\r\n");
          out.write("                        </TBODY>\r\n");
          out.write("                  </TABLE>\r\n");
          out.write("                </SPAN><SPAN \r\n");
          out.write("            style=\"DISPLAY: none\" id=Top1_1_divyi></SPAN></TD>\r\n");
          out.write("                <TD width=\"246\" colSpan=2 \r\n");
          out.write("            align=center>andy Tan</TD>\r\n");
          out.write("              </TR>\r\n");
          out.write("            </TBODY>\r\n");
          out.write("        </TABLE></TD>\r\n");
          out.write("      </TR>\r\n");
          out.write("    </TBODY>\r\n");
          out.write("  </TABLE>\r\n");
          out.write("</div>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /main.jsp(278,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty requestScope.hiList}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	<tr><td colspan=\"5\"><font color=\"red\">No information</font></td></tr>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /main.jsp(281,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty requestScope.hiList}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write('\r');
          out.write('\n');
          out.write('	');
          if (_jspx_meth_c_005fforEach_005f0(_jspx_th_c_005fif_005f3, _jspx_page_context))
            return true;
          out.write('\r');
          out.write('\n');
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f3, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f3);
      // /main.jsp(282,1) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.hiList}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /main.jsp(282,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("hi");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("    <TR>\r\n");
            out.write("      <TD bgColor=\"#ffffff\" height=\"26\" align=\"middle\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hi.hiID }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</TD>\r\n");
            out.write("      <TD bgColor=\"#ffffff\" align=\"middle\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hi.hiSection }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</TD>\r\n");
            out.write("      <TD bgColor=\"#ffffff\"><a href=\"./getHiByID?hiID=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hi.hiID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&action=info\" target=\"_blank\"><font color=\"#FFCC33\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hi.hiAddress }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</font></a></TD>\r\n");
            out.write("      <TD bgColor=\"#ffffff\" align=\"middle\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hi.hiShi }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("Room");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hi.hiTing }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("Living room");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hi.hiWei }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("Washroom");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hi.hiChu }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("Kitchen</TD>\r\n");
            out.write("      <TD bgColor=\"#ffffff\" align=\"middle\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hi.hiAction }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</TD>\r\n");
            out.write("      <TD bgColor=\"#ffffff\" align=\"middle\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hi.hiFloor }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</TD>\r\n");
            out.write("      <TD bgColor=\"#ffffff\" align=\"middle\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hi.hiArea }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</TD>\r\n");
            out.write("      <TD bgColor=\"#ffffff\" align=\"middle\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hi.hiPrice }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</TD>\r\n");
            out.write("      <TD bgColor=\"#ffffff\" align=\"middle\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hi.hiTime }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</TD>\r\n");
            out.write("      <TD bgColor=\"#ffffff\" align=\"middle\"><A href=\"./getHiByID?hiID=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hi.hiID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&action=info\" target=\"_blank\">Details</A></TD>\r\n");
            out.write("    </TR>\r\n");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent(null);
      // /main.jsp(302,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty requestScope.hiList}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("      <div align=\"center\">Total<font color=\"blue\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.rec }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</font>record\r\n");
          out.write("                ");
          if (_jspx_meth_c_005fif_005f5(_jspx_th_c_005fif_005f4, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("            ");
          if (_jspx_meth_c_005fif_005f6(_jspx_th_c_005fif_005f4, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("            ");
          if (_jspx_meth_c_005fforEach_005f1(_jspx_th_c_005fif_005f4, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("            ");
          if (_jspx_meth_c_005fif_005f7(_jspx_th_c_005fif_005f4, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("      </div>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f4, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f5_reused = false;
    try {
      _jspx_th_c_005fif_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f4);
      // /main.jsp(304,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.pageNum eq 1}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f5 = _jspx_th_c_005fif_005f5.doStartTag();
      if (_jspx_th_c_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest_005fnobody.reuse(_jspx_th_c_005fif_005f5);
      _jspx_th_c_005fif_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f4, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f6 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f6_reused = false;
    try {
      _jspx_th_c_005fif_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f4);
      // /main.jsp(305,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f6.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.pageNum ne 1}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f6 = _jspx_th_c_005fif_005f6.doStartTag();
      if (_jspx_eval_c_005fif_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" <a href=\"./index.jsp?pageNum=1\">First</a> <a\r\n");
          out.write("								href=\"./index.jsp?page=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.pageNum-1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">Previous</a> ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f6.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f6);
      _jspx_th_c_005fif_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f6, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f4, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f4);
      // /main.jsp(307,12) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.pageCountList}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /main.jsp(307,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("i");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write(" <a href=\"./index.jsp?pageNum=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a> ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f7(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f4, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f7 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f7_reused = false;
    try {
      _jspx_th_c_005fif_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f7.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f4);
      // /main.jsp(308,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f7.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.pageNum ne requestScope.pageCount}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f7 = _jspx_th_c_005fif_005f7.doStartTag();
      if (_jspx_eval_c_005fif_005f7 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" <a\r\n");
          out.write("								href=\"./index.jsp?pageNum=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.pageNum + 1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">Next</a> <a\r\n");
          out.write("								href=\"./index.jsp?pageNum=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.pageCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">Last</a>");
          int evalDoAfterBody = _jspx_th_c_005fif_005f7.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f7);
      _jspx_th_c_005fif_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f7, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f7_reused);
    }
    return false;
  }
}
